### ISSUE TITLE
About the simulation of the code

### ISSUE THREAD

**Issue by Yanxing-Shi** [ivalab/grasp_multiObject_multiGrasp#10]
I don't generate data of this code .
```
mainfileID = fopen(['/home/fujenchu/projects/deepLearning/deepGraspExtensiveOffline/data/grasps/scripts/trainttt' sprintf('%02d',folder) '.txt'],'a');
```
I do not quite understand the path of this line, how to modify it? I cannot generate valid data at this time.

**Comment by fujenchu** [comment]
My bad. You can simply ignore this line.
