### ISSUE TITLE
how can i train with this code

### ISSUE THREAD

**Issue by weiwuhuhu** [ivalab/grasp_multiObject_multiGrasp#11]
hello, 
    when i train with the  ./experiments/scripts/train_faster_rcnn.sh 0 graspRGB res50, then i find that there is no ./tools/test_net.py, and i meet the wrong with it, and how can i resolve it.Thank you your early reply.

**Comment by fujenchu** [comment]
Hi weiwuhuhu, 

My apology for late reply.
Please refer to #14 for this issue. Thank you.

Best,
Fu-Jen
