### ISSUE TITLE
Is there a ros version?

### ISSUE THREAD

**Issue by QiuYilin** [ivalab/grasp_multiObject_multiGrasp#12]
I want to realize this function with ros. Just ask for unnecessary labor.

**Comment by fujenchu** [comment]
Hi QiuYilin,

Sorry for the late reply.
Actually, yes. We just made a ROS version but it is still in private repo. Do you still need it?

Best,
Fu-Jen

**Comment by QiuYilin** [comment]
yeah thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fu-Jen (Richard) Chu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月1日(星期天) 下午2:11
收件人:&nbsp;"ivalab/grasp_multiObject_multiGrasp"<grasp_multiObject_multiGrasp@noreply.github.com&gt;;
抄送:&nbsp;"YilinQiu"<qiu.yilin@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ivalab/grasp_multiObject_multiGrasp] Is there a ros version? (#12)




Hi QiuYilin,
 
Sorry for the late reply.
 Actually, yes. We just made a ROS version but it is still in private repo. Do you still need it?
 
Best,
 Fu-Jen

**Comment by QiuYilin** [comment]
My email is 401447708@qq.com


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fu-Jen (Richard) Chu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月1日(星期天) 下午2:11
收件人:&nbsp;"ivalab/grasp_multiObject_multiGrasp"<grasp_multiObject_multiGrasp@noreply.github.com&gt;;
抄送:&nbsp;"YilinQiu"<qiu.yilin@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ivalab/grasp_multiObject_multiGrasp] Is there a ros version? (#12)




Hi QiuYilin,
 
Sorry for the late reply.
 Actually, yes. We just made a ROS version but it is still in private repo. Do you still need it?
 
Best,
 Fu-Jen

**Comment by DKurome** [comment]
> My email is 401447708@qq.com
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Fu-Jen (Richard) Chu"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月1日(星期天) 下午2:11 收件人:&nbsp;"ivalab/grasp_multiObject_multiGrasp"<grasp_multiObject_multiGrasp@noreply.github.com&gt;; 抄送:&nbsp;"YilinQiu"<qiu.yilin@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [ivalab/grasp_multiObject_multiGrasp] Is there a ros version? (#12) Hi QiuYilin, Sorry for the late reply. Actually, yes. We just made a ROS version but it is still in private repo. Do you still need it? Best, Fu-Jen — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I would like one, too     email：535892008@qq.com

**Comment by honghongzhenbang** [comment]
Can you send it to me if convenient. My email is 724685681@qq.com
Thank you very much.

**Comment by honghongzhenbang** [comment]
> Hi QiuYilin,
> 
> Sorry for the late reply.
> Actually, yes. We just made a ROS version but it is still in private repo. Do you still need it?
> 
> Best,
> Fu-Jen

Can you send it to me if convenient. My email is 724685681@qq.com
Thank you very much.

**Comment by pv33** [comment]
@fujenchu 
Can it not just be added here? Or maybe added to ivaROS repository with instructions on how to integrate with this codebase? There is no need to stay in private repo.

**Comment by JiaYangSun** [comment]
> Hi QiuYilin,
> 
> Sorry for the late reply.
> Actually, yes. We just made a ROS version but it is still in private repo. Do you still need it?
> 
> Best,
> Fu-Jen

could you please send it to me if it's convenient ？My email is 1399504891@qq.com,
Thank you

**Comment by fujenchu** [comment]
Dear All, 

[ROS version](https://github.com/ivaROS/ros_deep_grasp) of this work is here at our ivaROS!
Please let me know if you have problem accessing to it.

Thanks!
