### ISSUE TITLE
Code for evaluation

### ISSUE THREAD

**Issue by stefan-ainetter** [ivalab/grasp_multiObject_multiGrasp#13]
Hi @fujenchu, can you share the code for evaluation? Thanks!

**Comment by fujenchu** [comment]
Hi eifel699,

My apology for late reply.
Please refer to [this code](https://github.com/ivalab/grasp_multiObject_multiGrasp/blob/master/tools/eval_graspRGD.py~) for evaluation. However, you will need to redirect the path in line 277 to your text file with all test file paths. You can either download our pre-trained model or train your own network.

Please let me know if you have any further question!
Best,
Fu-Jen
