### ISSUE TITLE
How to convert from rgbd to rgd image?

### ISSUE THREAD

**Issue by Jigar-Joisar** [ivalab/grasp_multiObject_multiGrasp#15]
Can you share the code to convert rgb and depth image into rgd image.

**Comment by fujenchu** [comment]
Hi Jigar-Joisar, 

My apology for late reply. 
Please refer to [this toolbox](https://github.com/ivalab/grasp_multiObject/blob/master/rgbd2rgd.m) for converting function. Thank you!

Please let me know if you have further question!
Fu-Jen
