### ISSUE TITLE
Cornell Data Preprocessing

### ISSUE THREAD

**Issue by CZ-Wu** [ivalab/grasp_multiObject_multiGrasp#3]
Could you tell me which codes are  for preprocessing the Cornell dataset?

**Comment by fujenchu** [comment]
We will transform it to python scripts and push them to here. 
If you are in urgent, please send an email to fujenchu@gatech.edu, and I'll send you the original matlab code.

**Comment by lscandhmx** [comment]
Dear Fu，I don't know how to convert Cornell dataset to rgd. In dataPreprocessingTest_fasterrcnn_split.m，I don't knoww how each path comes from.Thank you very much!
