### ISSUE TITLE
 convert Cornell dataset to rgd

### ISSUE THREAD

**Issue by lscandhmx** [ivalab/grasp_multiObject_multiGrasp#4]
Dear Fu，I don't know how to convert Cornell dataset to rgd. I hope you can tell me more detail, Thank you very much!

**Comment by fujenchu** [comment]
Hi Iscandhmx, 
Sorry for the late reply.

For your convenience, please use this link:
https://www.dropbox.com/s/yjgedkrnzz8nds7/grasps320all.zip?dl=0

This file contains resized/cropped Cornell dataset for the RGB/RGD versions. The preprocessing code on the github augments training data and collects paths for testing set here. Please let me know if you have further issues.

Fu-Jen

**Comment by Marcelbgit** [comment]
Dear Fu, I'm using your resized/cropped dataset above and formated my dataset following the VOC rules.
But there are still errors about the path in the train.txt. I already changed the numbers to the name of the pcd0100cposCropped320.txt, but it didn't changed the Error. Hopefully you can help me out

IOError: [Errno 2] No such file or directory: '/home/grasp_multiObject_multiGrasp/data/grasps/01_Cropped320/pcd0100rCropped320.png 84.415625 180.074844 39.841938 18.498237 -0.076635.txt'
Command exited with non-zero status 1
1.14user 0.47system 0:01.09elapsed 147%CPU (0avgtext+0avgdata 199864maxresident)k
0inputs+0outputs (0major+61638minor)pagefaults 0swaps

Marcel

**Comment by jinhuan-hit** [comment]
Hi, @fujenchu 
The file of grasps320all.zip doesn't include Annotations and ImageSets files.Could give me some advice to train the model using the cornell grasp dataset?
