### ISSUE TITLE
Error when runing the demo

### ISSUE THREAD

**Issue by Juzhan** [ivalab/grasp_multiObject_multiGrasp#5]
My env:
+ ubuntu 14.04
+ python 2.7
+ tensorflow 1.4.0
+ cuda 8.0
+ cudnn 6.0
---
I followed the README to run the demo step by step:
1. clone the repository
2. build cython modules
3. install coco
4. download pretrain models

Everything was fine untill I run the demo: `./tools/demo_graspRGD.py --net res50 --dataset grasp`,
then I got an error:
```
2018-12-28 20:55:48.853153: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-28 20:55:48.930862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Quadro K2200 major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:03:00.0
totalMemory: 3.94GiB freeMemory: 5.62MiB
2018-12-28 20:55:48.930895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro K2200, pci bus id: 0000:03:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "./tools/demo_graspRGD.py", line 196, in <module>
    tag='default', anchor_scales=[8, 16, 32])
  File "/home/zhan/ws/grasp_multiObject_multiGrasp/tools/../lib/nets/network.py", line 306, in create_architecture
    rois, cls_prob, bbox_pred = self.build_network(sess, training)
  File "/home/zhan/ws/grasp_multiObject_multiGrasp/tools/../lib/nets/resnet_v1.py", line 155, in build_network
    scope=self._resnet_scope)
  File "/home/zhan/.local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py", line 207, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "/home/zhan/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/zhan/.local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 215, in stack_blocks_dense
    net = block.unit_fn(net, rate=1, **unit)
TypeError: bottleneck() argument after ** must be a mapping, not tuple
```
Did someone meet this error before?
I also try on ubuntu 18.04 with python 3.6, tensorflow 1.9.0, but still saw the same error.

**Comment by JuZhan** [comment]
Well, I found a solution and it works well: just use `tensorflow 1.1.0`

---
I found the same error in this issue: https://github.com/endernewton/tf-faster-rcnn/issues/134

By the way, there is something I need to modify when I run the `./tool/demo_graspRGB.py`.
1. change line 149 of `demo_graspRGB.py`:
https://github.com/ivalab/grasp_multiObject_multiGrasp/blob/fd28efd71832c3588bdbfddaa4a0c915a1ce76fa/tools/demo_graspRGD.py#L149
to
    ```
    savepath = './data/demo/results_all_cls/' + str(image_name)
    ```
2. create a folder named `results_all_cls` under ./data/demo, make sure the demo folder structure looks like this:
   ```
   ./data/demo
   ├── mask.jpg
   ├── pcd0100r_rgd_preprocessed_1.png
   ├── pcd0266r_rgd_preprocessed_1.png
   ├── pcd0882r_rgd_preprocessed_1.png
   ├── rgd_0000Cropped320.png
   └── results_all_cls   ----->    this is the result folder
   ```
3. then the code works like a charm :sunglasses:

**Comment by Juzhan** [comment]
Well, I found a solution and it works well: just use `tensorflow 1.1.0`

---
I found the same error in this issue: https://github.com/endernewton/tf-faster-rcnn/issues/134

By the way, there is something I need to modify when I run the `./tool/demo_graspRGB.py`.
1. change line 149 of `demo_graspRGB.py`:
https://github.com/ivalab/grasp_multiObject_multiGrasp/blob/fd28efd71832c3588bdbfddaa4a0c915a1ce76fa/tools/demo_graspRGD.py#L149 to

    ```
    savepath = './data/demo/results_all_cls/' + str(image_name)
    ```
2. create a folder named `results_all_cls` under ./data/demo, make sure the demo folder structure looks like this:
   ```
   ./data/demo
   ├── mask.jpg
   ├── pcd0100r_rgd_preprocessed_1.png
   ├── pcd0266r_rgd_preprocessed_1.png
   ├── pcd0882r_rgd_preprocessed_1.png
   ├── rgd_0000Cropped320.png
   └── results_all_cls   ----->    this is the result folder
   ```
3. then the code works like a charm :sunglasses:

**Comment by jinhuan-hit** [comment]
I meet the same issue with tf 1.10.0.Do we have to use tf 1.1.0 or other solutions?

**Comment by fujenchu** [comment]
Yes, we didn't change the code according to the updates of tensorflow so far. tf 1.1.0 is required. Thanks you.

**Comment by futurev** [comment]
change the "block" code in resnet_v1.py:
 for example: resnet50:
  blocks = [
      resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
      resnet_v1_block('block2', base_depth=128, num_units=4, stride=2),
      resnet_v1_block('block3', base_depth=256, num_units=6, stride=2),
      resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
  ]

**Comment by thuongtrannc** [comment]
I changed blocked as **futurev** comment.

`blocks = [
        resnet_v1.resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
        resnet_v1.resnet_v1_block('block2', base_depth=128, num_units=4, stride=2),
        resnet_v1.resnet_v1_block('block3', base_depth=256, num_units=23, stride=2),
        resnet_v1.resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
        ]`

There is no "bottleneck()" error, but it raises another error

`Invalid argument: ValueError: operands could not be broadcast together with shapes (3249,1) (12996,1)
`
Do you have any idea about that error?

**Comment by thuongtrannc** [comment]
Stride is not correct. So I changed to:

`
blocks = [
        resnet_v1.resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
        resnet_v1.resnet_v1_block('block2', base_depth=128, num_units=4, stride=2),
        resnet_v1.resnet_v1_block('block3', base_depth=256, num_units=6, stride=1),
        resnet_v1.resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
        ]
`

It worked for me!

**Comment by Juzhan** [comment]
It seems likes this problem is fixed, I close the issue.
