### ISSUE TITLE
Error by using your Dataset

### ISSUE THREAD

**Issue by Marcelbgit** [ivalab/grasp_multiObject_multiGrasp#6]
Dear Fu, I'm using your resized/cropped dataset above and formated my dataset following the VOC rules.
But there are still errors about the path in the train.txt. I already changed the numbers to the name of the pcd0100cposCropped320.txt, but it didn't changed the Error. Hopefully you can help me out

IOError: [Errno 2] No such file or directory: '/home/grasp_multiObject_multiGrasp/data/grasps/01_Cropped320/pcd0100rCropped320.png 84.415625 180.074844 39.841938 18.498237 -0.076635.txt'
Command exited with non-zero status 1
1.14user 0.47system 0:01.09elapsed 147%CPU (0avgtext+0avgdata 199864maxresident)k
0inputs+0outputs (0major+61638minor)pagefaults 0swaps

Marcel

**Comment by fujenchu** [comment]
Hi @Marcelbgit,
Could you confirm that the image is located at the path showed in the error message please? Also, it seems the program is looking for `/home/grasp_multiObject_multiGrasp/data/grasps/01_Cropped320/pcd0100rCropped320.png 84.415625 180.074844 39.841938 18.498237 -0.076635.txt` as a path, which might be wrong.

Thanks
