### ISSUE TITLE
Something wrong when split the cornell dataset

### ISSUE THREAD

**Issue by jinhuan-hit** [ivalab/grasp_multiObject_multiGrasp#8]
When I run dataPreprocessingTest_fasterrcnn_split.m,I find something strange as below.First,

mainfileID = fopen(['/home/fujenchu/projects/deepLearning/deepGraspExtensiveOffline/data/grasps/scripts/trainttt' sprintf('%02d',folder) '.txt'],'a');
...........
fclose(mainfileID);

However,there isn't the function fprintf to write something in trainttt.txt.I think you want to record something but miss the code.Second,

    filenum = str2num(imgname(4:7));
    if(any(test_list == filenum))
        file_writeID = fopen(imgSetTest,'a');
        fprintf(file_writeID, '%s\n', [imgDataDir(1:end-3) 'Cropped320_rgd/' imgname '_preprocessed_1.png' ] );
        fclose(file_writeID);
        continue;
    end

I can not understand the path of test.txt.Why not the same as train.txt?Just differ from the image_index.The last problem is that the image_indexs in test.txt don't have the 
corresponding pcdXXXXr_preprocessed_XX.txt in Annotations and pcdXXXXr_preprocessed_XX.png in ImageSets.

**Comment by stefan-ainetter** [comment]
Hi @jinhuan-hit,
I faced the same issues regarding the data preprocessing of the cornell dataset. Did you manage to solve the issues by your own? And if so, would you mind sharing the code that worked for you? 

Thanks!

**Comment by fujenchu** [comment]
No, you don't need trainttt at all. I believe it was left there for some historic issue, and I forgot to remove it. You will only need train.txt and test.txt which will be generated after you run this script. Hope this helps and my apology for late reply!

Best,
Fu-Jen
